name: BudgetManager
description: A simple AngularDart app
version: 0.0.2

homepage: https://budget-manager-gc.appspot.com
author: Your Name <amelieelibh@gmail.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: '>=3.0.0 <4.0.0'
  modal_dialog: "^2.0.0"
  angular_components: "^0.5.2"
  
  ng_bootstrap: '^0.6.3'
  
  fixnum: ^0.10.5
  intl: '>=0.14.0 <0.16.0'
  
  #js: ^0.6.1
  #uuid: ^0.5.3
  
  #uri: "^0.11.0"
  #rpc: "^0.5.6+3"
  http_server: "^0.9.6"
  appengine: '>=0.4.0 <0.5.0'
  
  logging_handlers: ^0.8.0
  
dev_dependencies:
  browser: "^0.10.0+2"
  dart_to_js_script_rewriter: "^1.0.2"
  
dependency_overrides:
  #quiver: '>=0.17.0 <0.22.0'
  #uri: "^0.10.0"
  
transformers:
#- di
#- angular2:
#    platform_directives:
#    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
#    platform_pipes:
#    - 'package:angular2/common.dart#COMMON_PIPES'
#    entry_points: web/main.dart
- dart_to_js_script_rewriter
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      Observable: 'package:observable/observable.dart'
      Profiler: 'package:perf_api/perf_api.dart'
      Window: 'dart:html'
